### ISSUE TITLE
Do you have any example code you can share?

### ISSUE THREAD

**Issue by HEXbody** [michaelloistl/ContextLabel#16]
Many projects on Github have example code in the attached project to make it more obvious how to use the library.

**Comment by michaelloistl** [comment]
@HEXbody I thought the code snippets in the readme would make the use clear as it's just a UILabel subclass. Anyway I will add an example shortly.

**Comment by HEXbody** [comment]
I thought they were pretty clear, but I'm unable to get this working.  I've declared a field to be a contextLabel in a reusable cell.  I'm struggling with a EXC_BAD_ACCESS error when I assign anything to it.

**Comment by michaelloistl** [comment]
Ok, will add a tableView example as well then...

**Comment by HEXbody** [comment]
I'm passed the EXC_BAD_ACCESS error, but now my touchResult.linkResult is always nil even though ContextLabel is correctly creating the right links and coloring them.  Any ideas?

**Comment by michaelloistl** [comment]
@HEXbody have added a sample project.
I have also fixed an issue where `touchResult.linkResult` would be nil when the view bounds.height would be different to the intrinsicSize.height (that would happen when you set the frame manually rather than using autoLayout).
I hope that's fixing the issue for you. If not please open a new issue and provide some sample code showing how you setup ContextLabel.
New version (1.2.1) will be available via CocoaPods shortly.
